

CREATE TABLE IF NOT EXISTS articles (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  description TEXT NOT NULL,
  content TEXT NOT NULL,
  link_image TEXT NOT NULL,
  type_article TEXT NOT NULL,
  total_view INT DEFAULT 0,
  daily_view INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_articles_title ON articles (title);
CREATE INDEX IF NOT EXISTS idx_articles_type_article ON articles (type_article);

-- Enable Row Level Security
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Add policy for public read access
CREATE POLICY "Allow public read access" 
  ON articles 
  FOR SELECT 
  TO anon 
  USING (true);

-- Insert sample article data
INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('The Future of AI in Healthcare', '2024-01-15', 'How artificial intelligence is revolutionizing medical diagnostics and patient care', 
'<p>Artificial intelligence is rapidly transforming the healthcare industry, offering unprecedented opportunities to improve patient outcomes, reduce costs, and enhance the efficiency of medical services.</p>
<p>Recent advancements in machine learning algorithms have enabled AI systems to analyze medical images with accuracy rivaling that of experienced radiologists. These systems can detect subtle abnormalities in X-rays, MRIs, and CT scans that might be missed by human eyes, leading to earlier diagnosis of conditions like cancer, heart disease, and neurological disorders.</p>
<p>Beyond diagnostics, AI is also making significant strides in personalized medicine. By analyzing vast amounts of patient data, including genetic information, medical history, and lifestyle factors, AI can help physicians develop tailored treatment plans that take into account the unique characteristics of each patient.</p>
<p>In hospital settings, AI-powered predictive analytics are being used to forecast patient admissions, optimize staffing levels, and manage resources more effectively. This not only improves operational efficiency but also ensures that patients receive timely care when they need it most.</p>
<p>Pharmaceutical companies are leveraging AI to accelerate drug discovery and development. Traditional methods of identifying potential drug candidates can take years and cost billions of dollars. AI algorithms can rapidly screen millions of chemical compounds, predicting their effectiveness and potential side effects, thereby significantly reducing the time and cost involved in bringing new medications to market.</p>
<p>Despite these promising developments, challenges remain. Issues related to data privacy, algorithm bias, and regulatory approval continue to be areas of concern that must be addressed as AI becomes more integrated into healthcare systems.</p>
<p>As we look to the future, the collaboration between human healthcare providers and AI systems will likely define a new era of medicine—one where technology enhances rather than replaces the human touch that is so essential to quality care.</p>',
'https://images.pexels.com/photos/7579831/pexels-photo-7579831.jpeg', 'technology');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('Global Climate Summit Yields New Commitments', '2024-02-05', 'World leaders agree on ambitious targets to reduce carbon emissions by 2030', 
'<p>In a historic gathering of world leaders, the Global Climate Summit concluded yesterday with unprecedented commitments to combat climate change. Representatives from over 190 countries participated in the two-week conference, which many experts are calling a turning point in international climate policy.</p>
<p>The summit''s final agreement, known as the "Green Future Accord," establishes a framework for reducing global carbon emissions by 50% by the year 2030, with the ultimate goal of achieving carbon neutrality by 2050. This ambitious target exceeds previous international commitments and reflects growing recognition of the urgent need to address climate change.</p>
<p>Developed nations, which have historically been the largest contributors to greenhouse gas emissions, have committed to providing $100 billion annually to help developing countries transition to clean energy sources and adapt to the impacts of climate change. This financial commitment represents a significant increase from previous funding pledges.</p>
<p>The accord also includes provisions for regular monitoring and verification of each country''s progress toward meeting its emissions reduction targets. An independent international body will be established to oversee this process and ensure transparency and accountability.</p>
<p>Notably, the agreement places emphasis on the protection of forests and oceans, which play crucial roles in absorbing carbon dioxide from the atmosphere. Participating countries have committed to ending deforestation by 2025 and establishing marine protected areas covering at least 30% of the world''s oceans by 2030.</p>
<p>While the Green Future Accord has been widely praised for its ambition, some environmental activists argue that the commitments do not go far enough to address the scale and urgency of the climate crisis. Critics point to the lack of legally binding mechanisms to enforce compliance with the agreement''s provisions.</p>
<p>Nevertheless, market analysts note that the clear policy signals sent by the summit have already begun to influence investment decisions, with renewable energy stocks experiencing significant gains following the announcement of the accord. This suggests that the private sector is increasingly aligning its strategies with the global transition to a low-carbon economy.</p>
<p>As countries begin the challenging work of implementing their climate commitments, the success of the Green Future Accord will ultimately be measured by its ability to catalyze real-world emissions reductions and help the world avoid the most catastrophic impacts of climate change.</p>',
'https://images.pexels.com/photos/2990650/pexels-photo-2990650.jpeg', 'politics');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('Revolutionary Electric Vehicle Battery Extends Range to 800 Miles', '2024-01-28', 'New solid-state battery technology promises to eliminate range anxiety for EV drivers', 
'<p>In a breakthrough that could accelerate the global transition to electric vehicles, researchers at NanoVolt Technologies have unveiled a new solid-state battery capable of powering an electric car for up to 800 miles on a single charge. This development, announced yesterday at the International Energy Innovation Conference, represents more than double the range of the best batteries currently available on the market.</p>
<p>The new battery technology, which has been under development for over five years, utilizes a novel solid electrolyte material that allows for higher energy density while significantly reducing the risk of fire or explosion associated with conventional lithium-ion batteries. Additionally, the solid-state design enables faster charging, with the ability to reach 80% capacity in just 15 minutes.</p>
<p>Dr. Elena Rodriguez, lead scientist at NanoVolt Technologies, explained that the breakthrough came from a fundamental rethinking of battery architecture. "We''ve replaced the liquid electrolyte used in traditional lithium-ion batteries with a proprietary solid material that allows lithium ions to move more efficiently between electrodes," she said. "This not only improves safety but also enables us to pack more energy into the same space."</p>
<p>Major automakers have already expressed interest in the technology. AutoElectric, one of the world''s largest electric vehicle manufacturers, has announced a strategic partnership with NanoVolt to incorporate the new batteries into its upcoming models, with production vehicles expected to hit the market by late 2025.</p>
<p>Industry analysts predict that this advancement could be the tipping point that drives mainstream adoption of electric vehicles. "Range anxiety has consistently been cited as one of the primary barriers to EV adoption," said Marcus Chen, senior analyst at Global Transport Research. "A battery that can deliver 800 miles on a single charge effectively eliminates that concern for most consumers."</p>
<p>Beyond the automotive sector, the technology also holds promise for renewable energy storage, potentially providing a more efficient means of storing power generated from intermittent sources like wind and solar. This could help address one of the key challenges in transitioning to a renewable energy grid.</p>
<p>While the initial cost of vehicles equipped with the new battery technology is expected to be higher than those with conventional batteries, NanoVolt projects that economies of scale will bring costs down to competitive levels within three to four years of mass production.</p>
<p>As governments around the world continue to implement policies aimed at reducing carbon emissions from transportation, innovations like this solid-state battery technology may play a crucial role in accelerating the shift away from fossil fuels and toward a more sustainable energy future.</p>',
'https://images.pexels.com/photos/9331077/pexels-photo-9331077.jpeg', 'technology');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('Record-Breaking Quarterback Signs Historic $500 Million Contract', '2024-02-10', 'Star player becomes highest-paid athlete in sports history with unprecedented 10-year deal', 
'<p>In a move that has sent shockwaves through the sports world, quarterback James Wilson has signed a record-breaking 10-year, $500 million contract with the San Francisco Pioneers. The deal, announced this morning at a press conference at the team''s headquarters, makes Wilson the highest-paid athlete in sports history.</p>
<p>The contract includes $300 million in guaranteed money and features a no-trade clause, giving Wilson unprecedented security and control over his future in the league. The annual average value of $50 million represents a 25% increase over the previous highest-paid player in the league.</p>
<p>Wilson, 27, has established himself as one of the premier talents in professional football, leading the Pioneers to championship victories in two of the past three seasons. Last year, he threw for 5,100 yards and 48 touchdowns while rushing for an additional 600 yards, earning him Most Valuable Player honors for the second time in his career.</p>
<p>Pioneers'' General Manager Sarah Thompson described the contract as an investment in the franchise''s future. "James isn''t just an exceptional athlete; he''s the cornerstone of our organization both on and off the field," Thompson said. "This contract reflects our belief that he will continue to lead our team to championships for years to come."</p>
<p>The deal has implications that extend far beyond the Pioneers. Sports economists suggest that Wilson''s contract will reset the market for elite quarterbacks, with several other star players likely to seek similar terms when their current deals expire. This could have significant ramifications for team salary caps and roster construction across the league.</p>
<p>Wilson, who grew up in modest circumstances in rural Ohio, expressed gratitude and a sense of responsibility that comes with the historic contract. "I''m incredibly blessed and humbled by this opportunity," he said. "My focus now is on working harder than ever to bring more championships to San Francisco and using my platform to make a positive impact in the community."</p>
<p>The quarterback has already established a foundation that provides educational resources and athletic opportunities to underprivileged youth, and he announced that he will be donating $50 million—10% of his new contract—to expand these initiatives.</p>
<p>Fan reaction to the massive deal has been largely positive, reflecting Wilson''s popularity and his contributions to the team''s recent success. Season ticket holder demand has reportedly spiked since the announcement, with the team''s ticket office reporting that their phones have been "ringing non-stop."</p>
<p>Wilson and the Pioneers will begin their quest for another championship when training camp opens next month, with expectations higher than ever following this historic contract announcement.</p>',
'https://images.pexels.com/photos/163452/basketball-dunk-blue-game-163452.jpeg', 'sports');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('New Study Reveals Surprising Benefits of Intermittent Fasting', '2024-01-22', 'Research shows improved cognitive function and longevity beyond weight management', 
'<p>A groundbreaking study published today in the Journal of Nutritional Science has revealed that intermittent fasting—a dietary approach that cycles between periods of eating and fasting—offers significant health benefits beyond weight management, including enhanced brain function and potentially increased longevity.</p>
<p>The research, conducted over a five-year period with more than 5,000 participants, is the largest and longest study of intermittent fasting to date. It challenges some conventional wisdom about optimal eating patterns and provides new insights into the biological mechanisms triggered by controlled fasting periods.</p>
<p>Lead researcher Dr. Michael Chen and his team at Pacific University found that participants who practiced intermittent fasting for at least three days per week showed marked improvements in cognitive performance, particularly in areas related to memory, focus, and problem-solving. Brain scans revealed increased neural connectivity and reduced inflammation in brain regions associated with higher cognitive functions.</p>
<p>"What surprised us most was the consistency of cognitive improvements across different age groups," said Dr. Chen. "While we expected to see some benefits, the extent to which intermittent fasting enhanced brain function—even in participants over 65—exceeded our hypotheses."</p>
<p>The study also documented several physiological changes associated with extended lifespan in previous animal studies. Participants who maintained intermittent fasting regimens showed reduced levels of inflammatory markers, decreased insulin resistance, and optimization of several longevity-associated genes. Blood analyses revealed a significant increase in autophagy—the body''s cellular cleaning and recycling process—which has been linked to slower aging and reduced risk of age-related diseases.</p>
<p>Different fasting protocols were examined in the study, including the 16:8 method (16 hours of fasting with an 8-hour eating window), the 5:2 approach (five days of normal eating with two non-consecutive days of limited caloric intake), and alternate-day fasting. Interestingly, all methods produced benefits, though the 16:8 protocol showed the most consistent results across various health markers.</p>
<p>While the findings are promising, researchers caution that intermittent fasting may not be appropriate for everyone. "Pregnant women, people with certain medical conditions such as diabetes, and those with a history of eating disorders should consult healthcare providers before adopting any fasting regimen," advised Dr. Sophia Williams, a nutritionist who participated in the study.</p>
<p>The research team plans to continue following the study participants to assess the long-term impacts of intermittent fasting and to identify the optimal fasting protocols for different demographic groups. They are also initiating a new study to examine how various dietary compositions during eating periods might interact with the fasting benefits.</p>
<p>As interest in intermittent fasting continues to grow among health-conscious consumers and medical professionals alike, this research provides valuable scientific evidence to inform dietary recommendations and personal health decisions.</p>',
'https://images.pexels.com/photos/5212694/pexels-photo-5212694.jpeg', 'health');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('Major Exhibition Celebrates Contemporary African Art', '2024-02-18', 'Landmark showcase features works from emerging and established artists across the African continent', 
'<p>The Metropolitan Art Museum has unveiled "Vibrant Visions: Contemporary African Perspectives," a landmark exhibition celebrating the diversity and innovation of current African art. The exhibition, which opened to the public yesterday, features over 200 works from 45 artists representing 18 African countries, making it one of the most comprehensive showcases of contemporary African art ever presented.</p>
<p>Curated by Dr. Nala Mensah, the exhibition challenges Western preconceptions about African art while highlighting the continent''s vibrant contemporary art scene. "For too long, African art has been viewed through a limited lens that emphasizes traditional forms and overlooks the dynamic, multifaceted nature of contemporary artistic expression across the continent," said Dr. Mensah. "This exhibition aims to correct that narrative by showcasing the incredible diversity and sophistication of today''s African art landscape."</p>
<p>The exhibition is organized thematically rather than geographically, exploring concepts such as urban transformation, environmental concerns, political resistance, gender identity, and the interplay between tradition and modernity. This approach emphasizes the universal elements in the artists'' work while acknowledging the specific cultural and historical contexts that inform their perspectives.</p>
<p>Featured prominently in the exhibition is Lagos-based artist Chioma Onyeka, whose large-scale mixed-media installations incorporate recycled materials to comment on consumerism and environmental degradation. Onyeka''s centerpiece, "Plastic Dreams," transforms thousands of discarded plastic bottles into a luminous, ethereal chandelier that dominates the museum''s central hall.</p>
<p>Also garnering significant attention is the work of Moroccan photographer Yousef Benali, whose striking portrait series "Faces of the Medina" documents the changing character of traditional neighborhoods in Marrakech. Using a distinctive color palette that juxtaposes vibrant traditional attire against modern architectural elements, Benali captures the tension between preservation and progress in contemporary North African urban spaces.</p>
<p>South African multimedia artist Thabo Mkhize presents a series of digital works that blend animation, sound, and interactive elements to explore post-apartheid national identity. Visitors can engage directly with his piece "Voices of Freedom," which incorporates audio testimonies from across generations to create a layered narrative of South Africa''s ongoing journey toward social justice.</p>
<p>The exhibition has already drawn record crowds, with opening weekend attendance exceeding the museum''s projections by nearly 40%. Critics have praised the show for its ambitious scope and thoughtful curation, with The Art Review calling it "a revelatory experience that demands a reconsideration of contemporary art''s global landscape."</p>
<p>In conjunction with the exhibition, the museum is hosting a series of events including artist talks, panel discussions, film screenings, and workshops designed to deepen public engagement with contemporary African art. Additionally, a comprehensive catalog featuring essays by leading scholars in the field will be published next month.</p>
<p>"Vibrant Visions: Contemporary African Perspectives" will remain on display through August 15, after which a modified version of the exhibition will tour to museums in Paris, Tokyo, and Johannesburg.</p>',
'https://images.pexels.com/photos/2570059/pexels-photo-2570059.jpeg', 'culture');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('Tech Startup Launches Innovative Urban Farming Solution', '2024-02-03', 'New vertical farming technology promises to revolutionize food production in cities', 
'<p>GreenStack, a technology startup focused on sustainable agriculture, has unveiled an innovative vertical farming system designed to transform urban food production. The company''s new "UrbanHarvest" platform, launched at the Sustainable Future Conference, combines advanced hydroponics, artificial intelligence, and renewable energy to grow fresh produce in dense urban environments with minimal resources.</p>
<p>The system utilizes specially designed modular growing units that can be stacked vertically in unused urban spaces such as warehouses, basements, or rooftops. Each module is equipped with LED lighting calibrated to optimal growing spectrums, automated nutrient delivery systems, and environmental controls that create ideal conditions for plant growth regardless of external weather conditions.</p>
<p>What sets GreenStack''s technology apart from existing vertical farming solutions is its proprietary AI system, which continuously monitors and adjusts growing conditions based on plant development. The system collects data from thousands of sensors monitoring factors such as moisture levels, nutrient density, and plant growth rates, then uses machine learning algorithms to optimize conditions for each crop variety.</p>
<p>"Traditional agriculture is increasingly vulnerable to climate change, requires vast amounts of land and water, and depends on long supply chains to get food to urban consumers," said Dr. Jasmine Park, GreenStack''s founder and CEO. "Our technology addresses these challenges by bringing food production directly into cities, reducing transportation needs and creating resilient local food systems."</p>
<p>The company claims its vertical farms use 95% less water than conventional farming methods, require no pesticides, and can produce yields up to 350 times greater per square foot of land. The controlled environment also allows for year-round growing seasons, unaffected by external climate conditions.</p>
<p>GreenStack has already secured partnerships with two major grocery chains to supply locally grown produce to urban stores. The first commercial-scale UrbanHarvest facility is currently under construction in Chicago, with operations expected to begin by mid-summer. This 50,000-square-foot facility will produce an estimated 2 million pounds of leafy greens, herbs, and select vegetables annually.</p>
<p>The company is also launching a smaller-scale system designed for restaurants, schools, and community centers. These "MicroHarvest" units occupy about 500 square feet and can produce enough fresh greens and herbs to supplement the needs of a mid-sized restaurant or cafeteria.</p>
<p>Urban planning experts see significant potential in the technology. "As cities continue to grow and climate change affects traditional agriculture, innovations like GreenStack''s system could play a crucial role in food security," said Professor Martin Rodriguez of the Urban Sustainability Institute. "Additionally, localizing food production reduces the carbon footprint associated with transporting food long distances."</p>
<p>While the initial installation costs remain higher than traditional farming infrastructure, GreenStack projects that ongoing technological improvements and economies of scale will make vertical farming economically competitive with conventional agriculture within five years, particularly for high-value crops in regions with high land costs or challenging growing conditions.</p>',
'https://images.pexels.com/photos/2284170/pexels-photo-2284170.jpeg', 'technology');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('Archaeologists Discover Ancient City in Amazon Rainforest', '2024-01-08', 'LiDAR technology reveals extensive urban complex challenging previous understanding of pre-Columbian civilizations', 
'<p>In a discovery that is reshaping our understanding of pre-Columbian civilizations, archaeologists have uncovered the remains of a vast urban complex hidden beneath the Amazon rainforest. The ancient city, estimated to have been inhabited between 1000 and 1400 CE, extends over approximately 30 square kilometers and includes elaborate road networks, reservoirs, defensive structures, and monumental architecture.</p>
<p>The discovery was made possible by LiDAR (Light Detection and Ranging) technology, which uses laser pulses to penetrate the dense forest canopy and create detailed 3D maps of the ground surface below. This advanced remote sensing method revealed intricate patterns of human-made structures that had remained invisible to conventional archaeological surveys.</p>
<p>Dr. Isabella Fernandez, who leads the international research team, described the significance of the find: "This discovery forces us to reconsider our assumptions about the level of social complexity and technological advancement that existed in the Amazon basin before European contact. What we''re seeing is evidence of sophisticated urban planning, water management, and agricultural systems that could have supported a population of tens of thousands."</p>
<p>The city features a central plaza surrounded by what appear to be ceremonial structures, including pyramids reaching heights of up to 20 meters. Extending outward from this ceremonial core is a carefully planned grid of residential areas intersected by raised causeways that remained usable even during seasonal flooding. The entire complex was protected by a series of concentric defensive ditches and embankments.</p>
<p>Perhaps most impressively, the ancient engineers developed an extensive hydraulic system that captured and distributed rainwater through a network of canals, reservoirs, and aqueducts. This system not only provided water for drinking and agriculture but also helped manage the extreme seasonal variations in rainfall characteristic of the region.</p>
<p>Surrounding the urban center, researchers identified areas of raised fields that would have been used for intensive agriculture. These elevated growing surfaces, constructed from soil and organic matter, would have remained above water during the rainy season while retaining moisture during drier periods.</p>
<p>"This kind of intensive agriculture, combined with careful management of forest resources, could have sustained large populations in an environment that was previously thought to be unsuitable for supporting major settlements," explained Dr. Carlos Mendes, an archaeobotanist involved in the project.</p>
<p>The discovery adds to growing evidence that the Amazon rainforest, often portrayed as a pristine wilderness untouched by human civilization until recent times, has in fact been shaped by human activity for thousands of years. It also raises important questions about how these sophisticated societies managed to develop sustainable relationships with their environment—knowledge that could have relevance for contemporary challenges related to climate change and biodiversity loss.</p>
<p>Ground excavations at selected sites within the complex are scheduled to begin next dry season. These investigations will aim to recover artifacts and organic materials that can provide more detailed information about the daily life, cultural practices, and eventual decline of this remarkable Amazonian civilization.</p>',
'https://images.pexels.com/photos/3290068/pexels-photo-3290068.jpeg', 'science');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('International Space Station Welcomes First Commercial Tourism Module', '2024-01-30', 'Private aerospace company launches luxury accommodation pod for civilian space travelers', 
'<p>The International Space Station (ISS) has entered a new era with the successful docking of the Aurora Module, the first commercial space habitat designed specifically for civilian space tourism. Developed by Celestial Horizons, a private aerospace company, the module represents a significant milestone in the commercialization of low Earth orbit and the democratization of space travel.</p>
<p>The Aurora Module, measuring 12 meters in length and 4.5 meters in diameter, features luxury accommodations for up to six civilian passengers. The interior includes private sleeping quarters, panoramic Earth-viewing windows, dedicated research areas, and even a small gymnasium designed for exercise in microgravity. Unlike the utilitarian design of other ISS components, Aurora emphasizes comfort and aesthetics to enhance the experience for non-professional astronauts.</p>
<p>"Today marks the beginning of a new chapter in human spaceflight," said Dr. Richard Wong, CEO of Celestial Horizons, during a press conference following the successful docking. "For decades, space has been accessible only to government astronauts and a handful of extremely wealthy individuals. Aurora will help open the space frontier to a broader segment of humanity."</p>
<p>The module was carried to orbit aboard Celestial Horizons'' Pegasus heavy-lift rocket and autonomously docked with the ISS''s Harmony node after a three-day journey. NASA and international space agency personnel aboard the station will spend the next two weeks configuring the module and conducting safety verifications before the first civilian guests arrive.</p>
<p>While space tourism has seen several high-profile missions in recent years, these have typically been brief visits lasting only a few days. The Aurora Module is designed to host guests for extended stays of up to three weeks, providing a more immersive experience of life in orbit.</p>
<p>The first civilian mission to the Aurora Module is scheduled for March and will include a retired physics professor, a social media influencer, a lottery winner from Japan, and three undisclosed high-net-worth individuals. Each passenger has undergone three months of specialized training at Celestial Horizons'' facilities in Nevada to prepare for the rigors of spaceflight and life aboard the station.</p>
<p>While Celestial Horizons has not publicly disclosed the price per ticket, industry analysts estimate the cost at approximately $25 million per person for a two-week stay. Despite the high price tag, the company reports that all planned missions for the next three years are fully booked, with a substantial waiting list.</p>
<p>Beyond tourism, the Aurora Module will also serve as a platform for commercial research and education. Celestial Horizons has partnered with several universities and research institutions to conduct experiments in microgravity, particularly in areas such as materials science, biomedical research, and advanced manufacturing techniques that might benefit from space conditions.</p>
<p>The company has also developed an extensive educational program that will connect students from around the world with Aurora''s guests and crew through live video links, allowing young people to experience space exploration vicariously and potentially inspiring the next generation of scientists and engineers.</p>
<p>As commercial interest in low Earth orbit continues to grow, Celestial Horizons has already announced plans for a second, larger module to be launched in 2026, with the long-term goal of establishing an entirely private space station once the ISS reaches the end of its operational life later this decade.</p>',
'https://images.pexels.com/photos/586030/pexels-photo-586030.jpeg', 'science');

INSERT INTO articles (title, date, description, content, link_image, type_article) VALUES
('International Film Festival Celebrates Emerging Global Voices', '2024-02-13', 'Annual cinema showcase spotlights groundbreaking work from underrepresented filmmakers', 
'<p>The 43rd International Horizons Film Festival opened yesterday in a celebration of diverse cinematic voices from around the world. The ten-day event, renowned for discovering and elevating emerging talent, will screen 128 films from 53 countries, with a particular focus this year on works from regions typically underrepresented in mainstream cinema.</p>
<p>Festival director Maria Gonzalez emphasized the event''s commitment to amplifying new perspectives in her opening address. "In a world where a handful of commercial studios dominate global screens, festivals like ours play a crucial role in ensuring that fresh voices and innovative approaches to filmmaking can find their audience," she told the capacity crowd at the historic Grand Palace Theater.</p>
<p>This year''s program features a record number of debut features, with 45 films from first-time directors. The festival has also achieved gender parity in its main competition section, with works directed by women comprising exactly half of the 22 films competing for the prestigious Golden Horizon award.</p>
<p>Among the most anticipated premieres is "Whispers in the Wind," the first feature film ever submitted from Bhutan to compete in the festival''s main section. Directed by Tshering Dorji, the visually stunning drama explores the tension between tradition and modernity through the story of a young woman who returns to her remote mountain village after studying abroad.</p>
<p>Also generating significant buzz is "Concrete Dreams," a documentary by Lebanese filmmaker Zeinab Khalil that chronicles the creative resilience of young artists in Beirut following the devastating port explosion of 2020. The film, shot over two years on minimal equipment, has been praised by early viewers for its intimate portrayal of artistic expression as a form of healing and resistance.</p>
<p>The festival''s industry program has expanded this year to include a dedicated funding forum where selected projects can pitch to international producers and distributors. This initiative aims to address one of the most significant challenges facing independent filmmakers from developing regions: securing the financial support necessary to bring their visions to the screen.</p>
<p>"We''ve created this platform because we''ve seen too many brilliant scripts and concepts fail to materialize due to lack of funding connections," explained Gonzalez. "By directly connecting emerging filmmakers with industry decision-makers, we hope to help bridge that gap."</p>
<p>In addition to traditional theatrical screenings, the festival has embraced hybrid presentation formats that emerged during the pandemic. Select films and panel discussions will be available via the festival''s streaming platform, making the event accessible to global audiences who cannot attend in person.</p>
<p>Special retrospective programs will honor the contributions of Chilean director Isabel Marcos, whose groundbreaking works exploring political upheaval and personal identity in Latin America have influenced a generation of filmmakers, and Nigerian cinema pioneer Oluwaseun Adebayo, who passed away last year after a five-decade career that helped establish Africa''s largest film industry.</p>
<p>The festival will conclude with the world premiere of "Borderlands," an ambitious multinational project featuring five interconnected stories set along different international borders, each segment directed by a filmmaker from the region portrayed. This collaborative work, spanning four continents, exemplifies the festival''s mission to use cinema as a medium for cross-cultural dialogue and understanding.</p>',
'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg', 'entertainment');